name: GitHub Pages deploy
on:
  push:
    branches:
      - blog
jobs:
  checkout-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Node.js
      uses: actions/setup-node@master
      with:
        node-version: 18.16.1
    - run: yarn
    - run: yarn build
      env:
        EMAIL: hughfenghen@gmail.com 
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 